In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [7]:
df = pd.read_csv("energy.csv")

In [8]:
df.columns

Index(['relative compactness', 'surface area', 'wall area', 'roof area',
       'overall height', 'orientation', 'glazing area',
       'glazing area distribution', 'heating load (HL)', 'cooling load (CL)'],
      dtype='object')

In [9]:
dict(zip(df.dtypes.index,df.dtypes.values))

{'relative compactness': dtype('float64'),
 'surface area': dtype('float64'),
 'wall area': dtype('float64'),
 'roof area': dtype('float64'),
 'overall height': dtype('float64'),
 'orientation': dtype('int64'),
 'glazing area': dtype('float64'),
 'glazing area distribution': dtype('int64'),
 'heating load (HL)': dtype('float64'),
 'cooling load (CL)': dtype('float64')}

In [10]:
df

,relative compactness,surface area,wall area,roof area,overall height,orientation,glazing area,glazing area distribution,heating load (HL),cooling load (CL)
0,0.98,514.5,294.0,110.25,7.0,2,0.0,0,15.55,21.33
1,0.98,514.5,294.0,110.25,7.0,3,0.0,0,15.55,21.33
2,0.98,514.5,294.0,110.25,7.0,4,0.0,0,15.55,21.33
3,0.98,514.5,294.0,110.25,7.0,5,0.0,0,15.55,21.33
4,0.90,563.5,318.5,122.50,7.0,2,0.0,0,20.84,28.28
...,...,...,...,...,...,...,...,...,...,...
763,0.64,784.0,343.0,220.50,3.5,5,0.4,5,17.88,21.40
764,0.62,808.5,367.5,220.50,3.5,2,0.4,5,16.54,16.88
765,0.62,808.5,367.5,220.50,3.5,3,0.4,5,16.44,17.11
766,0.62,808.5,367.5,220.50,3.5,4,0.4,5,16.48,16.61
767,0.62,808.5,367.5,220.50,3.5,5,0.4,5,16.64,16.03

In [11]:
x = df.iloc[:,:-2]
y = df.iloc[:,-2:]

In [12]:
x

,relative compactness,surface area,wall area,roof area,overall height,orientation,glazing area,glazing area distribution
0,0.98,514.5,294.0,110.25,7.0,2,0.0,0
1,0.98,514.5,294.0,110.25,7.0,3,0.0,0
2,0.98,514.5,294.0,110.25,7.0,4,0.0,0
3,0.98,514.5,294.0,110.25,7.0,5,0.0,0
4,0.90,563.5,318.5,122.50,7.0,2,0.0,0
...,...,...,...,...,...,...,...,...
763,0.64,784.0,343.0,220.50,3.5,5,0.4,5
764,0.62,808.5,367.5,220.50,3.5,2,0.4,5
765,0.62,808.5,367.5,220.50,3.5,3,0.4,5
766,0.62,808.5,367.5,220.50,3.5,4,0.4,5
767,0.62,808.5,367.5,220.50,3.5,5,0.4,5

In [13]:
y

     heating load (HL)  cooling load (CL)
0                15.55              21.33
1                15.55              21.33
2                15.55              21.33
3                15.55              21.33
4                20.84              28.28
..                 ...                ...
763              17.88              21.40
764              16.54              16.88
765              16.44              17.11
766              16.48              16.61
767              16.64              16.03

[768 rows x 2 columns]

In [14]:
x['label1'] = y.iloc[:,[0]]
x['label2'] = y.iloc[:,[1]]

In [15]:
x

,relative compactness,surface area,wall area,roof area,overall height,orientation,glazing area,glazing area distribution,label1,label2
0,0.98,514.5,294.0,110.25,7.0,2,0.0,0,15.55,21.33
1,0.98,514.5,294.0,110.25,7.0,3,0.0,0,15.55,21.33
2,0.98,514.5,294.0,110.25,7.0,4,0.0,0,15.55,21.33
3,0.98,514.5,294.0,110.25,7.0,5,0.0,0,15.55,21.33
4,0.90,563.5,318.5,122.50,7.0,2,0.0,0,20.84,28.28
...,...,...,...,...,...,...,...,...,...,...
763,0.64,784.0,343.0,220.50,3.5,5,0.4,5,17.88,21.40
764,0.62,808.5,367.5,220.50,3.5,2,0.4,5,16.54,16.88
765,0.62,808.5,367.5,220.50,3.5,3,0.4,5,16.44,17.11
766,0.62,808.5,367.5,220.50,3.5,4,0.4,5,16.48,16.61
767,0.62,808.5,367.5,220.50,3.5,5,0.4,5,16.64,16.03

In [16]:
import os
os.getcwd()

'e:\\Learnings\\iNeuron\\Internship\\EcoComfort-Intelligent-Energy-Efficiency-for-Residential-Buildings\\EDA'

In [18]:
dir = 'e:\\Learnings\\iNeuron\\Internship\\EcoComfort-Intelligent-Energy-Efficiency-for-Residential-Buildings'

In [23]:
model_path = os.path.join(dir,'models','RandomForestRegressor0','RandomForestRegressor0.sav')

In [24]:
model_path

'e:\\Learnings\\iNeuron\\Internship\\EcoComfort-Intelligent-Energy-Efficiency-for-Residential-Buildings\\models\\RandomForestRegressor0\\RandomForestRegressor0.sav'

In [25]:
import joblib
model = joblib.load(model_path)

FileNotFoundError: [Errno 2] No such file or directory: 'e:\\Learnings\\iNeuron\\Internship\\EcoComfort-Intelligent-Energy-Efficiency-for-Residential-Buildings\\models\\RandomForestRegressor0\\RandomForestRegressor0.sav'

In [ ]:
input = [0.9,563.5,318.5,122.5,7,5,0,0]

In [ ]:
model.predict([input])

In [ ]:
model.predict([[0.9,563.5,318.5,122.5,7,5,0,0]])

In [ ]:
model.predict([[0.9,563.5,318.5,122.5,7,5,0,0]])[0][0]

In [ ]:
import pickle
with open(model_path,'rb') as f:
    model = pickle.load(f)

In [ ]:
model.predict([[0.9,563.5,318.5,122.5,7,5,0,0]])

In [ ]:
pred_data = pd.read_csv('energy_efficiency_05012023_122005.csv')

In [ ]:
model.predict(pred_data.values)

In [ ]:
result = []
for val in (model.predict(pred_data.values)):
                    result.append(val)

In [ ]:
result

In [ ]:
result2 = pd.DataFrame(result,columns=['HL_Prediction','CL_Prediction'])

In [ ]:
result2